// swift-tools-version: 5.9
//
// Standalone LodeDBCore Swift package, version 2.0.6.
// Generated by the LodeDB release workflow (swift/LodeDBCore/scripts/publish_swift_package.sh);
// do not edit by hand. Sources and issues live in https://github.com/Egoist-Machines/LodeDB.

import PackageDescription

let package = Package(
    name: "LodeDBCore",
    platforms: [
        .macOS(.v13),
        .iOS(.v16)
    ],
    products: [
        .library(name: "LodeDBCore", targets: ["LodeDBCore"])
    ],
    targets: [
        .binaryTarget(
            name: "LodeDBCoreFFI",
            url: "https://github.com/Egoist-Machines/LodeDB/releases/download/v2.0.6/LodeDBCoreFFI.xcframework.zip",
            checksum: "c72a6191ff642079764537cded5b1f3f9b39e7f1b7d21bd164588e042d8be3dc"
        ),
        .target(
            name: "LodeDBCore",
            dependencies: ["LodeDBCoreFFI"],
            linkerSettings: [
                .linkedFramework("Accelerate")
            ]
        )
    ]
)
