// swift-tools-version: 5.9
//
// Standalone LodeDBCore Swift package, version 1.3.2.
// Generated by the LodeDB release workflow (swift/LodeDBCore/scripts/publish_swift_package.sh);
// do not edit by hand. Sources and issues live in https://github.com/Egoist-Machines/LodeDB.

import PackageDescription

let package = Package(
    name: "LodeDBCore",
    platforms: [
        .macOS(.v13),
        .iOS(.v16)
    ],
    products: [
        .library(name: "LodeDBCore", targets: ["LodeDBCore"])
    ],
    targets: [
        .binaryTarget(
            name: "LodeDBCoreFFI",
            url: "https://github.com/Egoist-Machines/LodeDB/releases/download/v1.3.2/LodeDBCoreFFI.xcframework.zip",
            checksum: "a0f7a7a0f665a19198b93989dea74a91405a992487fc46d230119e7bbbd6772b"
        ),
        .target(
            name: "LodeDBCore",
            dependencies: ["LodeDBCoreFFI"],
            linkerSettings: [
                .linkedFramework("Accelerate")
            ]
        )
    ]
)
