// swift-tools-version: 5.9
//
// Standalone LodeDBCore Swift package, version 2.0.10.
// Generated by the LodeDB release workflow (swift/LodeDBCore/scripts/publish_swift_package.sh);
// do not edit by hand. Sources and issues live in https://github.com/Egoist-Machines/LodeDB.

import PackageDescription

let package = Package(
    name: "LodeDBCore",
    platforms: [
        .macOS(.v13),
        .iOS(.v16)
    ],
    products: [
        .library(name: "LodeDBCore", targets: ["LodeDBCore"])
    ],
    targets: [
        .binaryTarget(
            name: "LodeDBCoreFFI",
            url: "https://github.com/Egoist-Machines/LodeDB/releases/download/v2.0.10/LodeDBCoreFFI.xcframework.zip",
            checksum: "69d06ce958e9436ae987a319bdd6ac2431cc31be9b29e3d1ad5a0bee088ea4cd"
        ),
        .target(
            name: "LodeDBCore",
            dependencies: ["LodeDBCoreFFI"],
            linkerSettings: [
                .linkedFramework("Accelerate")
            ]
        )
    ]
)
